Switch to veracruz-v1 branch
veracruz-project/rust-optee-trustzone-sdk pull request #1
Opened 2021-11-23 22:52 UTC by mathias-arm

2021-11-24 14:42 UTC, dominic-mulligan-arm approved these changes

2021-11-24 15:51 UTC, ShaleXIONG approved these changes

2021-11-24 16:21 UTC, egrimley-arm requested changes
Should `.gitmodules` be updated as well? There seem to be three references to a branch called `veracruz` in there.

2021-11-29 17:15 UTC, mathias-arm commented
@egrimley-arm:  this PR only updates `.gitmodules` to point to `veracruz-v1` branch. I am not sure what other changes should be done.

2021-11-29 17:20 UTC, egrimley-arm commented
> @egrimley-arm: this PR only updates `.gitmodules` to point to `veracruz-v1` branch. I am not sure what other changes should be done.

Hm. I don't know any more. My comment makes no sense!

2021-11-29 17:20 UTC, egrimley-arm approved these changes

2021-11-29 17:21 UTC, merged